name: resgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit-dev
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - opencv-python
    - lpips
    - submodules/diff-gaussian-rasterization-abs
    - submodules/simple-knn